// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AudiosController from "./audios_controller"
application.register("audios", AudiosController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InformationsController from "./informations_controller"
application.register("informations", InformationsController)
